apiVersion: "nuclio.io/v1"
kind: "NuclioFunction"
metadata:
  name: mxnet
  namespace: nuclio
spec:
  runtime: python
  handler: python_executioner:start_from_nuclio
  build:
    noCache: true
    commands:
      - rm -rf DLScheduler
      - git clone https://github.com/Frans-Lukas/DLScheduler.git
      - apt-get update
      - apt-get -y install libopenblas-dev curl
      - "pip install mxnet pillow keras dload numpy tensorflow"
      - "pip install --upgrade google-cloud-storage"
