apiVersion: "nuclio.io/v1"
kind: "NuclioFunction"
metadata:
  name: lenet
  namespace: nuclio
spec:
  runtime: python
  handler: param_server_main:start_from_nuclio
  env:
    - name: HDFSCLI_CONFIG
      value: /tmp/.hdfscli.cfg
    - name: HADOOP_USER_NAME
      value: franslukas
  build:
    commands:
      - echo "[global]" >> /tmp/.hdfscli.cfg
      - echo "default.alias = dev" >> /tmp/.hdfscli.cfg
      - echo "[dev.alias]" >> /tmp/.hdfscli.cfg
      - echo "url = http://192.168.10.205:9870" >> /tmp/.hdfscli.cfg
      - echo "user = franslukas" >> /tmp/.hdfscli.cfg
      - "pip install mxnet hdfs"
